### ISSUE TITLE
Previews appearing in directory with org files.

### ISSUE THREAD

**Issue by artsi0m** [karthink/org-auctex#5]
![image](https://github.com/karthink/org-auctex/assets/87656471/7b33c939-908a-4b79-9762-655a0d1ae7d3)

## Setup 
1. Howm [configured](https://github.com/artsi0m/emacs-organizer/tree/4c8e0cd3d28646a63fc65567cb5cf4a8a18ad481?tab=readme-ov-file#notes-personal-wiki-z-word--howm) to use org mode markup.
2. [org-auctex](https://github.com/artsi0m/emacs-organizer/tree/4c8e0cd3d28646a63fc65567cb5cf4a8a18ad481?tab=readme-ov-file#org-auctex-as-a-workaround-for-latex-previews-in-org-mode)

## What happens now
1. I create preview for latex formula with enabled preamble caching.
3. I type some term to search in howm.
4.  Within org files that contain search term  would also appear `_region_.tex` files with preambles.

## What would be nice
1. To have an ability to specify a directory for cached preambles using `:custom` keyword in use-package macro.

**Comment by karthink** [comment]
@artsi0m I'm not working on org-auctex any more.  Instead we're improving Org's built in latex preview system.  It works better than AucTeX previews, and will be merged into Org eventually.  Here's a [demo](https://www.youtube.com/watch?v=n-AfvuV-bYo) and [some instructions](https://abode.karthinks.com/org-latex-preview/) (showing newer features as well) if you'd like to try it right now.

**Comment by karthink** [comment]
j

**Comment by artsi0m** [comment]
> if you'd like to try it right now

I do. Also it would be nice to subscribe to news about development org-latex-preview. Ideally using rss, but email is fine too.

**Comment by karthink** [comment]
Updates are posted to the Org mailing list, you can search for the thread named "overhaul of the latex preview system".

If there are any user-facing changes I usually update that instructions page I linked to above.

**Comment by artsi0m** [comment]
Thanks. I think I can reply with problem that I have on windows just now.
